export const myData = [
  {
    id: 1,
    item: "sandal",
    prodname: "Black Pearl Flats",
    price: "₱315.00",
    image: require("./IMAGES/WOMEN/s1.png"),
    size: "400mm",
    background: "bg1",
  },
  {
    id: 2,
    item: "sandal",
    prodname: "Gold Pink Sequin",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s2.png"),
    size: "400mm",
    background: "bg2",
  },
  {
    id: 3,
    item: "sandal",
    prodname: "Peach Gold Flats",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s3.png"),
    size: "400mm",
    background: "bg3",
  },
  {
    id: 4,
    item: "sandal",
    prodname: "Velvet Red Flats",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s4.png"),
    size: "400mm",
    background: "bg4",
  },
  {
    id: 5,
    item: "sandal",
    prodname: "Black Zari Flats",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s5.png"),
    size: "400mm",
    background: "bg5",
  },
  {
    id: 6,
    item: "sandal",
    prodname: "Maron Gold Flats",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s6.png"),
    size: "400mm",
    background: "bg6",
  },
  {
    id: 7,
    item: "sandal",
    prodname: "Black Bling Flats",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s7.png"),
    size: "400mm",
    background: "bg7",
  },
  {
    id: 8,
    item: "sandal",
    prodname: "Boss Babe Flats",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/s8.png"),
    size: "400mm",
    background: "bg8",
  },
  {
    id: 9,
    item: "shoes",
    prodname: "Adida Arkyn Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws1.png"),
    size: "400mm",
    background: "bg1",
  },
  {
    id: 10,
    item: "shoes",
    prodname: "Adidas Continental Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws2.png"),
    size: "24.1cm",
    background: "bg2",
  },
  {
    id: 11,
    item: "shoes",
    prodname: "Adidas Periwinkle Orignals",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws3.png"),
    size: "24.1cm",
    background: "bg3",
  },
  {
    id: 12,
    item: "shoes",
    prodname: "Adidas Deerupt Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws4.png"),
    size: "24.1cm",
    background: "bg4",
  },
  {
    id: 13,
    item: "shoes",
    prodname: "Adidas Falcon Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws5.png"),
    size: "24.1cm",
    background: "bg5",
  },
  {
    id: 14,
    item: "shoes",
    prodname: "Adidas White Falcon Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws6.png"),
    size: "24.1cm",
    background: "bg6",
  },
  {
    id: 15,
    item: "shoes",
    prodname: "Adidas Supernova Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws7.png"),
    size: "24.1cm",
    background: "bg7",
  },
  {
    id: 16,
    item: "shoes",
    prodname: "Adidas Solat LT Orig",
    price: "₱3.00",
    image: require("./IMAGES/WOMEN/ws8.png"),
    size: "24.1cm",
    background: "bg8",
  },
];
